services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "8001:3000"
    env_file:
      - ./api-gateway/.env
    networks:
      - veren
    depends_on:
      - internal-redis

  # submission-service:
  #   build:
  #     context: ./submission-service
  #     dockerfile: Dockerfile.dev
  #   container_name: submission-service
  #   volumes:
  #     - ./submission-service:/src
  #   ports:
  #     - "8002:3000"
  #   env_file:
  #     - ./submission-service/.env
  #   command: [ "npm", "run", "dev" ]
  #   networks:
  #     - veren

  extractor-service:
    build:
      context: ./extractor-service
      dockerfile: Dockerfile.dev
    container_name: extractor-service
    volumes:
      - ./extractor-service:/src
      - clones-data:/src/src/clones
      - ./extractor-service/clones:/src/src/clones
    ports:
      - "8003:3000"
    env_file:
      - ./extractor-service/.env
    command: [ "npm", "run", "dev" ]
    networks:
      - veren
    depends_on:
      - internal-redis

  routing-service:
    build:
      context: ./routing-service
      dockerfile: Dockerfile.dev
    container_name: routing-service
    volumes:
      - ./routing-service:/src
      - clones-data:/src/src/clones
    ports:
      - "8004:3000"
    env_file:
      - ./routing-service/.env
    command: [ "npm", "run", "dev" ]
    networks:
      - veren 
  orchestrate-service:
    build:
      context: ./orchestrate-service
      dockerfile: Dockerfile.dev
    container_name: orchestrate-service
    volumes:
      - ./orchestrate-service:/src
    ports:
      - "8005:3000"
    env_file:
      - ./orchestrate-service/.env
    command: [ "npm", "run", "dev" ]
    networks:
      - veren  
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    container_name: notification-service
    volumes:
      - ./notification-service:/src
    ports:
      - "8007:3000"
    env_file:
      - ./notification-service/.env
    networks:
      - veren

  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile.dev
    container_name: backend-service
    volumes:
      - ./backend-service:/src
      - clones-data:/src/src/clones
    ports:
      - "8006:3000"
    env_file:
      - ./backend-service/.env
    command: [ "npm", "run", "dev"]
    networks:
      - veren
    depends_on:
      - internal-redis

  clone-worker:
    build:
      context: ./WORKERS/clone-worker
      dockerfile: Dockerfile.dev
    command: [ "npm", "run", "clone:worker" ]
    volumes:
      - ./WORKERS/clone-worker:/src
      - clones-data:/src/src/clones
    env_file:
      - ./WORKERS/clone-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis

  build-worker:
    build:
      context: ./WORKERS/build-worker
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./WORKERS/build-worker:/src
      - /var/run/docker.sock:/var/run/docker.sock
      - clones-data:/src/src/clones
    env_file:
      - ./WORKERS//build-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis

  internal-redis:
    image: redis:7
    container_name: notification_internal_redis
    restart: always
    networks:
      - veren
    volumes:
    - redis-data:/data

volumes:
  pgdata:
  dind-storage:
  clones-data:
  redis-data:

networks:
  veren:
    external: false