services:
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile.dev
    container_name: api-gateway
    ports:
      - "8001:3000"
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./packages/domain:/app/packages/domain
    networks:
      - veren
    depends_on:
      - internal-redis

  routing-service:
    build:
      context: ./routing-service
      dockerfile: Dockerfile.dev
    container_name: routing-service
    volumes:
      - ./routing-service:/src
      - clones-data:/src/src/clones
    ports:
      - "8004:3000"
    env_file:
      - ./routing-service/.env
    command: [ "npm", "run", "dev" ]
    networks:
      - veren 
  orchestrate-service:
    build:
      context: ./orchestrate-service
      dockerfile: Dockerfile.dev
    container_name: orchestrate-service
    volumes:
      - ./orchestrate-service:/src
    ports:
      - "8005:3000"
    env_file:
      - ./orchestrate-service/.env
    command: [ "npm", "run", "dev" ]
    networks:
      - veren  
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.dev
    container_name: notification-service
    volumes:
      - ./notification-service:/src
    ports:
      - "8007:3000"
    env_file:
      - ./notification-service/.env
    networks:
      - veren

  clone-worker:
    build:
      context: .
      dockerfile: ./WORKERS/clone-worker/Dockerfile
    volumes:
      - clones-data:/src/clone-worker/src/clones
    env_file:
      - ./WORKERS/clone-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis

  build-worker:
    build:
      context: .
      dockerfile: ./WORKERS/build-worker/Dockerfile
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - clones-data:/src/build-worker/src/clones
    env_file:
      - ./WORKERS//build-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis

  internal-redis:
    image: redis:7
    container_name: notification_internal_redis
    restart: always
    networks:
      - veren
    volumes:
    - redis-data:/data

volumes:
  pgdata:
  dind-storage:
  clones-data:
  redis-data:

networks:
  veren:
    external: false